### ISSUE TITLE
Suggestion: include option for Wadsmoosh as the choice of iwad

### ISSUE THREAD

**Issue by Star-X555** [obsidian-level-maker/Obsidian#110]
Because it'd be really neat to see Oblige generate hundreds of levels across multiple "games", each using their original themes.

The previous maintainer said no, but as this is a fork of Oblige, it can do so without issue, assuming the engine can handle that many randomly generated levels in one wad.

Failing an automatic generation of all maps, it'd be nice to have a way to generate a mapset for a given base game and have the maps and campaigns renamed/reordered to match Wadsmoosh's file order, so that I can just keep Wadsmoosh as the active iwad at all times and simply swap out individual campaigns within wadsmoosh with Oblige mapsets.

**Comment by ghost** [comment]
I think one of the potential challenges with a request like this is that the size and content of a Wadsmoosh iwad can be different depending on what IWADs the individual user merges, correct?

**Comment by Star-X555** [comment]
Hence why the second option was listed, namely matching the wadsmoosh map file names and episodic layout for a given map group.

E.g. Select Doom II (wadsmoosh) as the iwad, and it will generate Doom II style maps using wadsmoosh's mapset info as a base, without necessarily mucking with the other mapsets included in a given wadsmoosh iwad.

No idea how hard this would be to implement though.  I need to take a closer look at wadsmoosh's iwad/pk3 setup tbh, so I can offer more specific suggestions.

Edit: Looked at my Doom Complete pk3, and found that the map names are adjusted like so:
Doom 1 and 2: Unchanged.
Sigil: No idea how it was labeled in its original wad, but here it's listed as E5M1 through E5M9.
Master Levels: Renamed to ml_map01 through ml_map21 (yes, map is lower case).
Nerve's expansion (No Rest For The Living, I believe?): Renamed nv_MAP01 through nv_MAP09.
Plutonia: Renamed pl_MAP01 through pl_MAP32.
TNT: Renamed tn_MAP01 through tn_MAP32.

Theoretically, besides the episode option, all that'd be needed to get everything supported is to just provide an option to generate TNT and Plutonia mapsets with the option of naming the maps with the above standard, instead of using the default MAP01 through MAP32.

Also it looks like mapinfo is split between a main mapinfo file, which is the same every time, and separated mapinfo files for each wad included, with ones not part of the set being completely empty outside of a commented "placeholder" comment.  Theoretically this modular style of mapinfo means generating a set simply would require replacing the separate mapinfo files, as opposed to the main one, and would work regardless of which wads you included in wadsmoosh, available resources notwithstanding (e.g. can't use Doom 1 generation if you lack the Doom 1 resources in the wadsmoosh :p ).

**Comment by tempanon1** [comment]
There's also a few more additional options for Doom 1 and 2, the X-Box levels, which are listed as E1M10 and MAP33 respectively. I also kinda hope that the Jaguar and PSX Doom exclusive levels get added to WADSmoosh someday, but that would only further complicate things. I have found success as far as opening an Obsidian generated mapset, and simply renaming the maps to their WADSmoosh counterparts, like MAP01 into PL_MAP01 for Plutonia. I can even load several of them at once.

**Comment by ghost** [comment]
After considering how this would have to be implemented, it seems like a lot of effort and potential breakage of the Lua portions of Obsidian for a feature that a) Only works with one out of the seven (as of this comment) engine selections in the program, and b) Is a problem that can be effectively solved with a preset-capable launcher, of which there are many. 

In addition, errors with WadSmoosh itself or with a user's usage of it may lead to errors that they may attempt to attribute to Obsidian itself.
