### ISSUE TITLE
Batch command not working with Obsidian

### ISSUE THREAD

**Issue by Star-X555** [obsidian-level-maker/Obsidian#111]
When I try using a bash script like this:

> `#!/bin/bash`
> `./obsidian --install . --batch /home/starx555/doomresources/oblige/doom_complete_multiwads/doomrla_randommap_doom2.wad --load ./obsidian_default_doom2.txt` 

It gives the following error:

> `./doomrla_obsidian_doom2_mapgen.sh: line 2: 438136 Segmentation fault      (core dumped) ./obsidian --install . --batch /home/starx555/doomresources/oblige/doom_complete_multiwads/doomrla_randommap_doom2.wad --load ./obsidian_default_doom2.txt`

It worked fine on the old versions of Oblige, though those actually had the install tag applied automatically.  For whatever reason, it doesn't work.  The error is incredibly cryptic too, with no real log explaining WHY it can't do that.

Any chance of a fix soon?

**Comment by ghost** [comment]
This should work with Beta 18 and prior. It will be fixed before Beta 19 is fully released, but it is a byproduct of changing some of the GUI elements to sliders and checkboxes. 

Basically, at the moment, some functions are relying on the existence of a slider (for example) to pull a value from. In batch mode, this is not present, causing the segfault in your example by trying to use a non-existent pointer.

**Comment by ghost** [comment]
https://github.com/dashodanger/Obsidian/releases/tag/Obsidian-Beta19Preview10

Beta 19 Preview 10 should now finish batch mode successfully with default settings at least. I'll keep this open until it's properly sussed out with custom configs, though.

**Comment by Phytolizer** [comment]
Can we close this? It's been over a month with no more reports.

**Comment by ghost** [comment]
Agreed, but if anyone has segfaults again and needs to report it, please do, especially with a log attached if possible

**Comment by ghost** [comment]
This may have cropped up again with the Beta 19 release. Need to investigate further.

**Comment by ghost** [comment]
Looks like it was a call to the filename formatter which isn't really needed in batch mode anyway. The downloads have been updated with a fix.
