### ISSUE TITLE
Suggestion: allow for saving as .pk3 file instead of wad

### ISSUE THREAD

**Issue by Star-X555** [obsidian-level-maker/Obsidian#115]
Simply because most modern ports can handle pk3 files reasonably well,  and it's so much easier to move things around in what is basically a glorified zip.

**Comment by ghost** [comment]
PK3 support is definitely on the roadmap. The following link shows the "1.0" project goals; things that are targeted to be implemented before potentially having an initial release. You'll see PK3 supported listed in the left-hand column.

https://github.com/dashodanger/Obsidian/projects/1

**Comment by ghost** [comment]
I'm going to reopen this as I've attached this directly to the 1.0 project instead of just having an unlinked note

**Comment by ghost** [comment]
https://github.com/dashodanger/Obsidian/commit/8214086d97d79ae1815fb9c22f345057ec0d1789 adds the ability to compress the output WAD and optionally give it either a .zip or .pk3 extension. It is still just a singular WAD inside the archive, but this at least saves the user the inconvenience of doing it manually. As far as structuring the lumps inside of a folder as some engines can handle, it was decided by the team to not pursue that at this time.
