### ISSUE TITLE
Suggestion: include Brutal Oblige

### ISSUE THREAD

**Issue by alphatonic** [obsidian-level-maker/Obsidian#118]
A while ago when this add-on: https://gitlab.com/CloudOfShame/BrutalOblige still worked with the latest Brutal Doom or Project Brutality versions it brought lots of fun.

It should be included in Obsidian IMHO under the "Modded Game Extras" area if it is even possible.

**Comment by ghost** [comment]
Similar to https://github.com/dashodanger/Obsidian/issues/44 , addons that were compatible with Oblige 7.70 usually just need their Lua portions updated to the new format to work with Obsidian. I'd have to look more into Brutal Oblige to see if anything else would be needed.

**Comment by GTD-Carthage** [comment]
This should really be brought up to the original authors rather than our team here

**Comment by alphatonic** [comment]
Okay sorry for spamming the issues forum. Sadly the author has disappeared it seems.

**Comment by ghost** [comment]
I imagine that the mod should still work with Oblige 7.70. For what it's worth, https://github.com/dashodanger/Obsidian/releases/tag/Oblige-770-Enhanced is our last release of Oblige's 7.70 codebase with some quality of life improvements.
