### ISSUE TITLE
3D Models

### ISSUE THREAD

**Issue by VxLonewolfxV** [obsidian-level-maker/Obsidian#119]
3D models like the 3d doors shown on this video, https://www.youtube.com/watch?v=4PbsH4iOIK0
maybe 3d decorate like vehicles, houses, buildings, DINOSAURS!, PLANETS!, A WHOLE GALAXY!, LOL .

**Comment by ghost** [comment]
With compatibility for Hexen format/UDMF in progress, there will likely be prefabs that take advantage of polyobjects, but the 3D models you are describing are most likely outside of Obsidian's scope for the time being. 3D model packs that replace enemies/weapons/items in supported engines should work with the maps Obsidian generates, though.

**Comment by VxLonewolfxV** [comment]
oh i see,... btw thx for keeping oblige alive, i still think is the best thing that ever happened to doom xD.
