### ISSUE TITLE
"IWAD style mode" overrides "level size" setting

### ISSUE THREAD

**Issue by tukkek** [obsidian-level-maker/Obsidian#130]
Hi, not a bug in itself but more probably what I like to call a procedural-generation "blunder" (when things just go wrong for whatever reason). Thought you guys might like to look into it and see if it's just an odd case or something that can be improved.

Basically it's a Huge single-map (my first ever created with Obsidian! :D ) which can be finished by basically taking a couple right turns and reaching the exit. Beat it in literally a minute or two after launching... certainly doesn't feel "Huge" as advertised lol

(Attached PWAD removed)

**Comment by tukkek** [comment]
Generated another one with the same options and while a bit longer, also could be beaten in about a minute and a half flat.

I'm using the latest tagged released by the way (d6bbe4b6e).

(Attached PWAD removed)

**Comment by tukkek** [comment]
I've tried creating a Transcendent-size map and by the looks of the preview minimap (and speed it took to create), it has no more than 5 rooms and a corridor. Definitely not the same size map I'd expect from the original Oblige so definitely looks like something  fishy is going on when it comes to the map size setting...

I'm setting up all the 3 sliders to the same value (level size, upper bound and lower bound), in this case "75 (Transcendent)".

**Comment by tukkek** [comment]
Turning modules on and off, it seems that the problem lies with "IWAD style mode". When it's turned on, maps are tiny and when it's turned off it seems to generate map sizes as per the "level size" setting accordingly.

To be honest I have no idea what this option does but the description only mentions "architectural features", not map size or overriding other settings, nor is it labeled experimental, as some of the other options are.

**Comment by ghost** [comment]
IWAD style mode does, by design, override other parameters available to the user in order to more closely mimic levels in the original IWADs. Among these are level size. This is a case where we need to update the help documentation to be more verbose, but it is working as intended.

**Comment by tukkek** [comment]
Wouldn't you want to keep this open until the documentation is updated?

**Comment by ghost** [comment]
Correct; I updated the tooltip today with an addendum explaining the override of user settings. If you use the pre-made releases, then the next release should contain the update.

**Comment by tukkek** [comment]
Thanks! I'll update my local copy at some point and check out the newest b19!

**Comment by tukkek** [comment]
Just read the new tooltip and while it does in fact now warn users about how this overrides other options, it doesn't really explain what the options is for those like me who don't know (ie. why would I want to use it or not use it)? Is that grounds for reopening this issue or creating a new one?

**Comment by ghost** [comment]
The issue, which you rightly brought up, is that the tooltip/help did not give the user a fair warning that it would override their other settings. This has been resolved. As new modules (such as IWAD mode) are developed, their descriptive documentation will evolve as well.
