### ISSUE TITLE
Missing textures?

### ISSUE THREAD

**Issue by tukkek** [obsidian-level-maker/Obsidian#131]
This is a map I uploaded to issue #130 which has a red-and-yelllow exclamation mark near the exit:

(Generated PWAD removed; logs indicate Modded Game Extras was enabled)

I'm uploading a new one that has the same icon right at the starting room: 
(Generated PWAD removed; logs indicate Modded Game Extras was enabled)

I have the *Obsidian epic resource pack* module enabled, with the *merge textures* checkbox activated and using `GZDoom g4.5.0`.

**Comment by tukkek** [comment]
I updated to 4.6.0 and can still see the icon on the second map ("Tragic concourse").

**Comment by tukkek** [comment]
I turned off *Obsidian epic resouce pack* and played a couple of Huge maps. Didn't come across any exclamation-marks on the first one but did find half a dozen or so of them on the second map, usually right on top of items or in places where it looks like where items might be spawned at (but weren't).

![Screenshot_20210717_032945](https://user-images.githubusercontent.com/3819826/126028668-3a551d51-5beb-45ef-b3e3-ea96d2c92285.png)

(Generated PWAD removed; logs indicate Modded Game Extras was enabled)

Unrelated, really but you guys may also want to tone down the flashing walls a bit. They're OK on the less brightly-lit environments but when they're very colorful and rapidly-flashing, I'm pretty sure they're getting close to seizure-inducing material for those sensitive to it. I'm sure none of the devs have (potentially) [killing someone](https://www.epilepsy.com/learn/about-epilepsy-basics/how-serious-are-seizures) in mind while working on this, so I thought I'd make note of it. If anyone thinks it warrants its own issue, I'd be happy to have them or myself open one for this particular concern.

**Comment by tukkek** [comment]
As mentioned in the other issue, I'm using a clone of the most recent tag (d6bbe4b).

**Comment by Phytolizer** [comment]
I was able to confirm the last screenshot. Looking through your OBLIGDAT now, thanks for uploading the wad.

**Comment by Phytolizer** [comment]
![image](https://user-images.githubusercontent.com/9062746/126037491-1464e7c0-9485-44a3-984d-92e5755357cb.png)
(Generated PWAD removed; logs indicate Modded Game Extras was enabled)
Version of the same WAD with the same seed but Debug Control options set to ON. Notable is the different choice of prefabs and enemy placement, but that's a separate issue. I again encountered an exclamation mark, but in a secret this time.

**Comment by Phytolizer** [comment]
[LOGS.txt](https://github.com/dashodanger/Obsidian/files/6834724/LOGS.txt)

**Comment by GTD-Carthage** [comment]
Looks like Modded Game Extras is activated on the log - I recommend disabling D4T entities (unless playing Death Foretold) and QCDE Lootboxes (unless playing QC:DE)

**Comment by tukkek** [comment]
I can confirm that I don't have *Modded Game Extras* enabled. I don't think I ever had but definitely not since creating this issue and these maps - because I haven't fiddled with Obsidian nor generated or played any map since.

**Comment by Phytolizer** [comment]
An unintuitive thing about current Obsidian is that when a module is unchecked, its contents are still "active" (enabled when checked). You probably enabled D4T entities, "minimized" the module, and forgot about it. The log I posted shows this to be the case  using your config.

**Comment by Phytolizer** [comment]
![image](https://user-images.githubusercontent.com/9062746/126083972-f2374bf7-d3c3-41ab-bd6c-f5ffe7696752.png)

**Comment by tukkek** [comment]
Just checked my config file and apparently you're right. Should I make a new issue regarding options not being disabled when their module is disabled? That's **extremely** counter-intuitive user-interface design.

**Comment by Phytolizer** [comment]
Resolved?

**Comment by tukkek** [comment]
> Resolved?

Good call. I'll close it for now and reopen if I have this problem again with B19. Thanks all!

**Comment by tukkek** [comment]
About the epilepsy hazard though: does anyone else here thinks it merits its own issue?

**Comment by ghost** [comment]
An epilepsy warning traditionally has been included with games themselves (in the intro and such); I recommend approaching source port developers and maintainers if you are concerned about this. People suffering from epilepsy should exercise caution when consuming any visual media.
