### ISSUE TITLE
More involved secrets

### ISSUE THREAD

**Issue by Phytolizer** [obsidian-level-maker/Obsidian#132]
Most of the secrets in Obsidian are just "notice a thing, immediately get a reward". I'm wondering how feasible it is for a hidden switch to be hidden across the room from its associated item. For example, you see a suspicious wall, but the switch to open it is hidden in some other prefab. Maybe it would be too confusing, but I think secrets could get some more love in this area.

**Comment by tukkek** [comment]
I was thinking exactly the same thing after trying out Obsidian for the first time recently! "Secrets" are not very secret at all as even a new-ish player like me can immediately spot them at a glance and activate them.

In comparison, switches can be a tricky to find. Why not use the existing switch logic (and I mean *switch rooms* specifically, not *switch goals*) and have one unlock access to a room with guaranteed no monsters but items/ammo? Honestly finding a cool new weapon (or even ammo or health) would be a lot more exciting, gameplay-wise than a power-up, as it happens to be my experience with 90%+ of secrets in the original Oblige (i fact, a `Secret loot: power-up | items | random` option in itself would be great too)!

Looks like all the mechanisms already exist in the codebase: locked rooms, switches, balanced item generation/placement... Hopefully would not be too hard to just put them to use in making "secret areas" worth their name and be more exciting to find!

**Comment by tukkek** [comment]
Just for reference, I think the current misaligned-texture secrets are excellent. They are easy to miss while you're trying to clear a room or if you're bactracking without paying much attention. When you are paying close attention to the environment though, they are not hat hard to spot and it's always a rewarding feeling of "something's....amiss, let me try this".

That might be a good baseline for thinking of good secret design: not obvious, not too obscure, rewards you for simply being mindful while playing the game without being distracting or gimmicky and feels immediately rewarding when that "ah-ha" moment comes and you uncover it.

When discussing these topics it's often hard to agree on what "good" is, especially when each person may have its own preferences but I thought I'd drop my own view on why this particular type of secret feels good and like a natural fit for the game.

**Comment by Phytolizer** [comment]
After some discussion in the discord, this depends on the ability to mark the switch's target as optional, so that secrets do not become part of the map progression by mistake. In other words, there are some significant code changes required here.
