### ISSUE TITLE
Change module toggle from checkboxes to something more intuitive

### ISSUE THREAD

**Issue by Phytolizer** [obsidian-level-maker/Obsidian#143]
> Just checked my config file and apparently you're right. Should I make a new issue regarding options not being disabled when their module is disabled? That's **extremely** counter-intuitive user-interface design.

_Originally posted by @tukkek in https://github.com/dashodanger/Obsidian/issues/131#issuecomment-882126250_

**Comment by Phytolizer** [comment]
The easy fix to this issue is to make the checkboxes into arrows, as that implies collapsing as opposed to disabling the module's contents.

**Comment by ghost** [comment]
Agreed, will be changed before Beta 20 comes out

**Comment by ghost** [comment]
Looking at https://github.com/dashodanger/Obsidian/issues/131#issuecomment-882126250 , the implication is that Modded Game Extras was effectively enabled when unchecked. I have been unable to replicate this behavior with a fresh install. I will keep this open, but I have changed the issue title to reflect the fact that we still need to change the module toggle appearance.

If you do indeed have the appearance of D4T entities or QC:DE items with modded_game_extras showing as zero (disabled), please post the WAD and logs in question.

**Comment by ghost** [comment]
Change has landed in unstable with the following commit:
https://github.com/dashodanger/Obsidian/commit/42750ac727b0bd4ad9eb5b81dd2f6878ebdea878
