### ISSUE TITLE
Linearity slider

### ISSUE THREAD

**Issue by tukkek** [obsidian-level-maker/Obsidian#147]
I have no idea how realistic an option like this is but I've been finding myself trending more and more towards big one-off levels rather than full WADs. They feel pretty good as-is and most maps are fine but one downside is that there's a lot of potential for backtracking - and while that comes with the territory, obviously, and I don't mind *some backtracking*, it doesn't feel good to have 3 keys and be searching for forever for that 3-key door you probably missed way-back-when on a tiny alcove behind a box or something.

Most maps turn out just fine even on the higher-ends of the level sizes but if there was a "linearity" slider that could be adjusted to ever-so-slightly nudge the map into less individually-branching paths to curb on some of that overwhelming complexity and backtracking, it would be very welcome - either as a slider or one of those options where you can simply select "slightly more" or "slightly less" (linear).

I apologize if I missed anything (other than "linear mode" which really is not the same idea) but with new settings like "symmetry" and "room size/area count" soft-sliders, perhaps this will fit right into the direction Obsidian is going.

I guess ,ideally if you turned this hypothetical setting to max you'd get basically the same results as a "linear mode" map.

**Comment by ghost** [comment]
I think I understand what you're asking; the vanilla Doom/SLUMP option has a "Forkiness" slider, which when reduced to 0%, makes the kind of completely linear level you are referring to. I think that the solution on the Obsidian map gen side might have to do with implementing an alternate shape grammar, as I think the grow/sprout steps produce some of the branching. Will look more into it.

**Comment by ghost** [comment]
After poking around more and testing, I feel that there would be a combination of Obsidian settings that would help with what you're looking for. Linear Mode, combined with Linear Start and things like reducing Switch Goals/Three key doors to 'NONE' would likely reduce both forking and backtracking to meet your needs. Anything further would likely require editing the shape grammar, located at /games/(gamename)/shapes.lua and limiting the conn, symmetry, and mirror rules for new rooms.

**Comment by tukkek** [comment]
I am not looking for linear maps and I definitely want keyed doors and three-keyed doors in my maps. I explicitly mentioned I am not interested in Linear Mode yet you are suggesting it to me now for some reason.

I appreciate your taking the time to look into it but I think you missed the point of this issue.

**Comment by ghost** [comment]
Like I said in my last response, any further reduction of physical branching other than what I suggested would likely require editing of the shape grammar to control the various Root/Grow/Sprout steps in a way that gives you the desired result. This is something that cannot be quantified with a simple slider. 

Also, in your own words:
"I guess, ideally if you turned this hypothetical setting to max you'd get basically the same results as a "linear mode" map."

This is why I brought up Linear Mode in combination with your other settings. You send a confusing message when you want a slider that can produce the same thing as Linear Mode, yet have a snarky response when I point that out.
