### ISSUE TITLE
Shop/closet dropdoown

### ISSUE THREAD

**Issue by tukkek** [obsidian-level-maker/Obsidian#148]
I thought I had seen something related to this but I can't seem to find it again. I like both the "shop" (where you press the button to pick which item you want) and the "closet" where you simply walk in and the other options are blocked but if I could choose between either, I'd just go with "closet" every time as this doesn't break the pacing of the game and has less options to choose.

The "shop" is a technical marvel to behold for someone who knows nothing about Doom modding and it definitely offers interesting decisions to make but I just like the "closet" better, personally. A drop-down where you could pick "closet, shop, both or none" would be great. It could also be implemented as two "less/some/more..."  options too like most of the other level features.

Again, I thought I had seen something like that at some point already, so I apologize if I'm missing something.

**Comment by ghost** [comment]
These fabs are limited to a single Lua file, games/doom/fabs/item/dem_item_gamble.lua . As opposed to making new permanent UI options with such a narrow scope, this is a case where a user is recommended to edit a prefab definition to their preferences. This could mean either editing the file itself or making an edited copy available as a selectable addon for Obsidian.

**Comment by tukkek** [comment]
Users don't edit prefabs, developers and contributors do.

**Comment by ghost** [comment]
Andrew Apted transitioned to Lua and prefabs WADs with Oblige for the express purpose of making it easier for users to customize their own install. This tradition continues with Obsidian.
