### ISSUE TITLE
[BUG] Script Error with Themes

### ISSUE THREAD

**Issue by mattbratt11** [obsidian-level-maker/Obsidian#274]
I tried to generate levels using Obsidian Beta 20 Preview, but it threw an error at the start of making the MAP01 Plan.
It gave me this error:

Attempt to index a nil value (global 'THEMES')

Is there any way to fix that?

**Comment by ghost** [comment]
If you are able to attach the LOGS.txt from the run that generated this error, it will help pinpoint the script that had an issue. Also, for basic troubleshooting, are you running this from a completely clean install, or did you copy it over an existing installation?

**Comment by mattbratt11** [comment]
[LOGS.txt](https://github.com/dashodanger/Obsidian/files/7600651/LOGS.txt)
This is the log file when it threw the error.
And yes, I even did the clean install of Obsidian Beta 20 Preview.

**Comment by ghost** [comment]
[zdoom_armaetus_epic_textures.zip](https://github.com/dashodanger/Obsidian/files/7600739/zdoom_armaetus_epic_textures.zip)

I think this might fix it. There is a file in this zip called zdoom_armaetus_epic_textures.lua. If you place it in the /modules folder, and overwrite the one that is already there, it should work. I'll keep this open until that's confirmed though.

**Comment by mattbratt11** [comment]
I did, and it worked. Thanks!

**Comment by ghost** [comment]
Ok, I folded it into upstream as https://github.com/dashodanger/Obsidian/commit/0cf6d5681991080af95683ab97bf382e14b22593 and will close this. Thanks for the report.
