### ISSUE TITLE
Can't find OBSIDIAN.exe file inside the .zip file

### ISSUE THREAD

**Issue by lgyzus** [obsidian-level-maker/Obsidian#345]
I cant seem to find the obsidian.exe file after I extract the zip, I can't find it either with the "go to file" button, can anyone help?

**Comment by RagnarRandom** [comment]
did you download the source or the release?

**Comment by lgyzus** [comment]
![image](https://user-images.githubusercontent.com/43282327/155740185-a9a77389-a894-417b-8fe6-869a09864699.png)
downoaded this one

**Comment by lgyzus** [comment]
https://github.com/dashodanger/Obsidian

**Comment by lgyzus** [comment]
the one u get from this link

**Comment by RagnarRandom** [comment]
yeah got the source not the binary release
click the "releases" link on the right side
![Untitled](https://user-images.githubusercontent.com/98027513/155762097-58224102-bd0f-4d4e-a277-9b064d1dba27.png)
which will take you to https://github.com/dashodanger/Obsidian/releases then you can download latest _stable_ release. which is beta 19 right now

**Comment by ghost** [comment]
@lgyzus your question has been answered properly by @RagnarRandom , but I will leave this open so that you can confirm you were able to find and run the program.

**Comment by ghost** [comment]
It's been about a week, so hopefully this means that you found the .exe and are playing through levels as we speak. I'll close this, but it can be reopened if you are still encountering issues.
