### ISSUE TITLE
i am interested in "freedoom-ifying" obsidian

### ISSUE THREAD

**Issue by RagnarRandom** [obsidian-level-maker/Obsidian#346]
i wanna go through and change all "UAC" references in the zdoom story generation lua scripts to AGM, as well as any images or anything else that might reference doom IP, to make a a version that will be totally libre.

what is the actual status of the images in the prefabs and epic texture pack? i recognize alot of it from freedoom, and pd paintings, but i would like to help replace anything that is not free, if there is anything. at the very least i wanna make a fork that is freedoom-centric referencing AGM in story and techbase textures.

**Comment by ghost** [comment]
For the first part of your question, it is entirely possible to create an addon that replaces the current story generation lua with Freedoom-centric verbiage without needing to fork the program. 

For the images, I will have to defer to the contributors who actually work on that content. I will see if one of them is available to address that here.

**Comment by RagnarRandom** [comment]
can you give me a short kinda walkthrough on making an addon?
do i just take all the stuff i modified in it's original structure in a folder called "freedoomified" then zip that folder and rename to pk3? will  running obsidian with an addon like that REPLACE the stuff that i modified, or just add it in to procedural generation? ie even with the addon it still could spit out the original stuff?

**Comment by ghost** [comment]
Let's say you want to replace zdoom_stories.lua with your version that references AGM instead. This file normally resides in the /modules folder of the Obsidian install. For your addon, you would make a folder called modules, and place your version of zdoom_stories.lua in it. Then you would zip that folder into a .pk3 with whatever name you see fit. When you enable that addon, PHYSFS will layer your /modules/zdoom_stories.lua over the original /modules/zdoom_stories.lua, effectively replacing it while the program is running. This all happens in a virtual file system, so you are not overwriting any of the original content, but for all intents and purposes the only version Obsidian will be aware of is yours.

**Comment by RagnarRandom** [comment]
ok, so an addon just patches the diff. gotcha
