### ISSUE TITLE
Compile error, and potential fix

### ISSUE THREAD

**Issue by andrewschott** [obsidian-level-maker/Obsidian#352]
On linux I had a compile error after doing a clean git pull (wiped my old dir and started fresh).

The error was:

```
Building CXX object CMakeFiles/obsidian.dir/source_files/obsidian_main/ui_window.cc.o
/home/andrew/workspace/git_repos/Obsidian/source_files/obsidian_main/ui_window.cc: In constructor ‘UI_MainWin::UI_MainWin(int, int, const char*)’:
/home/andrew/workspace/git_repos/Obsidian/source_files/obsidian_main/ui_window.cc:82:18: error: call of overloaded ‘add(const char [14], NULL, void (&)(Fl_Widget*, void*))’ is ambiguous
   82 |     menu_bar->add("Help/Tutorial", NULL, menu_do_tutorial);
      |     ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/FL/Fl_Choice.H:25,
                 from /usr/include/FL/Fl_Color_Chooser.H:32,
                 from /home/andrew/workspace/git_repos/Obsidian/source_files/obsidian_main/hdr_fltk.h:31,
                 from /home/andrew/workspace/git_repos/Obsidian/source_files/obsidian_main/ui_window.cc:21:
/usr/include/FL/Fl_Menu_.H:114:8: note: candidate: ‘int Fl_Menu_::add(const char*, int, void (*)(Fl_Widget*, void*), void*, int)’
  114 |   int  add(const char*, int shortcut, Fl_Callback*, void* = 0, int = 0); // see src/Fl_Menu_add.cxx
      |        ^~~
/usr/include/FL/Fl_Menu_.H:116:8: note: candidate: ‘int Fl_Menu_::add(const char*, const char*, void (*)(Fl_Widget*, void*), void*, int)’
  116 |   int  add(const char* a, const char* b, Fl_Callback* c, void* d = 0, int e = 0) {
      |        ^~~
gmake[2]: *** [CMakeFiles/obsidian.dir/build.make:860: CMakeFiles/obsidian.dir/source_files/obsidian_main/ui_window.cc.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:258: CMakeFiles/obsidian.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2
```

I went into the source and changed the aforementioned null to 0 and things built.  Not sure if its the best way to do the fix, but it built.  I had coded ages ago, and have forgotten damn near all of it, so this may or may not be a good remedy, but it worked.  And nice job on the new tutorial!  Looks nice.

**Comment by ghost** [comment]
Assuming your solution plays nice with MSYS/MinGW, it seems like the best solution to me. I'll test it and fold it in as a fix if everything goes well.

**Comment by ghost** [comment]
Looks good; I added your fix with commit https://github.com/dashodanger/Obsidian/commit/ce9bf67c5acb44eaa0147665770bdbaddf1a3245; I'm about to do another PR against the main repo so it should land there soon as well. Thanks for that catch!

**Comment by andrewschott** [comment]
Thanks, Ill look into this later on this afternoon and see if it works.  BTW, you need a spec file for linux rpms?  Or don't care?  I can do a set for rhel and fedora.

**Comment by ghost** [comment]
Hmm...honestly we haven't given any thought to an install option on Linux since the conversion from Makefiles to CMake. I can safely say that nobody is working on packaging at the moment, though, so I don't think we'd turn it down.

**Comment by andrewschott** [comment]
Well, my "install" was to copy what was needed to a folder and create a .desktop file to point there.  Can't say much would need to change aside from pointing to a standard directory rather than something in my /home dir.

Your call, as its your project.  If you have any preferences let me know, I can abide by them.

**Comment by ghost** [comment]
I'll ask the rest of the contributor team and get their preferences, and let you know
