### ISSUE TITLE
Is it possible to create a map with only straight lines?

### ISSUE THREAD

**Issue by PenguinDOOM** [obsidian-level-maker/Obsidian#360]
Only vertical and horizontal lines, not diagonal lines.

**Comment by ghost** [comment]
There are two ways Obsidian can accomplish this:

The first would involve selecting 'Vanilla Doom' as the game engine. This will switch the map generator internally from Obsidian's main generator to one called SLUMP. SLUMP is a fork of the SLIGE level generator, and will make maps like you describe, but they will be relatively simple in nature compared to the rest of the options.

The second would involve creating a custom version of what is known as shape grammar. Shape grammar, on a basic level, is a set of rules that determine how rooms are placed and then grown in a map layout. https://github.com/GTD-Carthage/Obsidian-Addons has an addon called 'Barebones Shape Grammar' if you wanted to experiment with such a thing.

**Comment by PenguinDOOM** [comment]
I tried the first method, but it didn't work as expected.
My purpose is to create something like a maze with only horizontal and vertical lines. (Maybe I'll have to manually tweak it later)
I will try the second method. To do that, you need to understand how the code works.

**Comment by ghost** [comment]
As far as the first method, do you mean that the SLUMP levels still don't look like the layout you were envisioning?

For the second, we have a reference in our wiki at https://github.com/dashodanger/Obsidian/wiki/Shape-Grammars

**Comment by ghost** [comment]
I am going to close this as the question has been answered to the extent of Obsidian's ability to accomplish such a task.

If you have a mind to experiment further, there is unused maze code in /scripts/automata.lua, but it is old/untested and I have no idea what it would take to implement it into the current map generator.
