### ISSUE TITLE
Installation support

### ISSUE THREAD

**Issue by Phytolizer** [obsidian-level-maker/Obsidian#365]
Tracking issue to encourage me to actually get this working with CMake. Once it works, releasing will be as simple as:
```console
cmake -DCMAKE_INSTALL_PREFIX="$PWD/install" --preset dist
cmake --build --preset dist
cmake --install build
```
and then zipping up the resulting folder.

**Comment by Phytolizer** [comment]
The end goal here is to make it so that CI builds can be tagged as the release and require literally 0 effort :)

**Comment by TiZ-HugLife** [comment]
Funny you should mention that; I'm working on a Flatpak build and gotten to the point where it builds, but doesn't install, because there's no "install" target. 😂 Guess I'll just manually copy everything where it's supposed to go.

**Comment by Phytolizer** [comment]
> Funny you should mention that; I'm working on a Flatpak build and gotten to the point where it builds, but doesn't install, because there's no "install" target. joy Guess I'll just manually copy everything where it's supposed to go.

Yeah I suppose this would be very useful for package maintainers. It's still on my radar, but I've been struggling to find time for it.

**Comment by TiZ-HugLife** [comment]
I can relate to that. It shouldn't be a particularly big deal to copy things over manually, though. 🙂

**Comment by Phytolizer** [comment]
@dashodanger, can you provide a list of directories which need to be copied into a full fresh Obsidian install?

**Comment by ghost** [comment]
Sure, so the required (even if empty) folders should be:
addons
data
engines
games
language
modules
scripts
theme
tools

EDIT: Under tools, filename_formatter is an essential binary that is built as well. qsavetex is technically not needed until Quake support evolves, but a missing filename_formatter will cause problems

EDIT EDIT: filename_formatter is now an internally linked library; disregard

**Comment by Phytolizer** [comment]
Thanks. I think it is working, so @HugLifeTiZ this might have been a small patch after all (it should be out in about an hour).

edit: haha jk it totally works!!

**Comment by Phytolizer** [comment]
Fixed by 73efd89b94560e9ef4fca09f8dac0841461947a9.

**Comment by TiZ-HugLife** [comment]
It looks like the install target does not actually put any of the files in the right place on Linux. The `$PREFIX` is definitely `/app` because FLTK puts all of its stuff in `/app/share`. I even set CMAKE_INSTALL_PREFIX manually. But there's no creation of `/app/bin/obsidian` nor any `/app/share/obsidian` directory, so I still have to do it manually. I don't *mind* doing it manually, but I thought I'd at least let you know.

**Comment by Phytolizer** [comment]
A good note. The current Obsidian executable depends on it being in the same directory as the data, so this might require some thought in the core program.

**Comment by Phytolizer** [comment]
Would you be ok with me just moving the installation destination to ${CMAKE_INSTALL_PREFIX}/share/obsidian? Any desktop entry would then point to share/obsidian/obsidian. @HugLifeTiZ

**Comment by andrewschott** [comment]
If y'all need a spec/srpm I just finished doing one.  Ironing out a few oddball errors, not sure if its my build or a new bug.  I can share a link or the spec once things are done on my end if anyone wishes.

@Phytolizer Regarding binary placement, my solution was to create a shell script in /usr/bin that cd's to /usr/share/obsidian and then launches the compiled binary.  This also fixes the problem of not being able to type "obsidian" at the cli to launch things.

**Comment by TiZ-HugLife** [comment]
Putting the binary in `$prefix/share/obsidian` shouldn't be too bad. Thanks to all the other changes recently that allow Obsidian to work without the working directory being the install_dir, we can just symlink `$prefix/bin/obsidian` to `$prefix/share/obsidian/obsidian` and it should be fine.

**Comment by ghost** [comment]
FYI, I may have to fold in filename_formatter as an internal library a la SLUMP/ZDBSP. I'm getting a couple of reports of locale issues from international users where the absolute path to the filename_formatter binary is getting mangled when sent to subprocess.h

**Comment by andrewschott** [comment]
OK.  Ironed out mostly everything.  Forgot to cp over from my buildroot a dir.  The above list sorted that out.  Just need to fine tooth comb the permissions, and I am done.

@HugLifeTiZ I tried just now for sh!ts and giggles the symlink thing, and for the release tarball as of ...5?.. days agao, this does NOT work.  If the git branch fixes this, I can incorporate into the specfile a symlink rather than the shell script.  FOr whatever reason my brain sees the symlink as better than a shell script.

Now that things are essentially done and working, the last little tidbit is what I should call the version?  @dashodanger I currently have it as 7.79.beta20.20220330 (harkening back to Oblige 7.70), so I can simply bump it appropriately and rpm/dnf will see it as a new update when the actual release is there.  But that is presuming alot.  What Is the actual version I should use?

**Comment by ghost** [comment]
There's a bit of conversation internally about that. I don't know what the ultimate result will be but it will probably be something more akin to an Ubuntu-style convention of Year.Month

**Comment by andrewschott** [comment]
@dashodanger Can I presume it will be at minimal not conflicting with 7.79?  22.4 is greater than 7.79.  As is 8.0.  I just dont want to have to deal with the repo hell of obsoleting just so the current packages when an official release is made with the proper versioning hammered out.

Thanks for the help, it is indeed greatly appreciated.

**Comment by TiZ-HugLife** [comment]
> @HugLifeTiZ I tried just now for sh!ts and giggles the symlink thing, and for the release tarball as of ...5?.. days agao, this does NOT work. If the git branch fixes this, I can incorporate into the specfile a symlink rather than the shell script. FOr whatever reason my brain sees the symlink as better than a shell script.

The work to get Obsidian to function with a working directory other than the install directory is *very* recent, within the last couple of days. Current git head does fix this.

**Comment by ghost** [comment]
> @dashodanger Can I presume it will be at minimal not conflicting with 7.79? 22.4 is greater than 7.79. As is 8.0. I just dont want to have to deal with the repo hell of obsoleting just so the current packages when an official release is made with the proper versioning hammered out.
> 
> Thanks for the help, it is indeed greatly appreciated.

Yeah, anything in the realm of 7.x, 8.x, etc will definitely not clash.

**Comment by andrewschott** [comment]
Cool.  And I see you made a new release :D  Time to play with that now :D

**Comment by ghost** [comment]
The CMake presets and install seem to be working, so closing this out
