### ISSUE TITLE
No option to turn enemy ZDoom marines off?

### ISSUE THREAD

**Issue by 4-and-a-half-star-games** [obsidian-level-maker/Obsidian#392]
In older versions there was a way to turn of ZDoom Marines, but now I can only make them appear as little as 'scarce', am I missing an option or is this intentional?

**Comment by ghost** [comment]
It sounds like you are leaving the module enabled.

![Capture](https://user-images.githubusercontent.com/58537100/158906320-9f7013bb-3f74-4d70-a095-135b82ff38a7.jpg)
 
This is how the module should appear when it is disabled. Are you still encountering ZDoom Marines when the module looks like this?

**Comment by 4-and-a-half-star-games** [comment]
Oh, that's enabling the module? I thought it was just opening the menu, my mistake.

**Comment by ghost** [comment]
All good, there's been a 50/50 split on users who wanted everything to be checkboxes and users who wanted modules with sub-options to have a +/- button to enable them. We've created a first-run tutorial that covers various GUI aspects including the situation that you ran into. It's currently in the Unstable release only, but will definitely be present in the next Stable release.

**Comment by 4-and-a-half-star-games** [comment]
Ah, thank you for your help. IMO, the +/- is fine as long as it's clear that it's enabling and disabling them instead of just opening and closing menus.
