### ISSUE TITLE
theme settings "Digger"

### ISSUE THREAD

**Issue by HytaleAdrRus** [obsidian-level-maker/Obsidian#40]
I just would like to see a new theme in the "theme settings" called "Digger" in which only metro, mines, stairs and elevators were generated. and nothing else. Is it possible to do this?

**Comment by ghost** [comment]
Short answer, yes. Long answer, it will probably be in the form of an (optional) addon versus a default option in the main program. Will post updates as this gets fleshed out.

**Comment by HytaleAdrRus** [comment]
Ok. I'm waiting

**Comment by ghost** [comment]
So a good solution for this was suggested, and honestly makes more sense than trying to code in themes for individual preferences. If you maintain a separate theme file and prefab directory, take out the things you don't want to appear, and swap that out when desired, it would accomplish the same effect.

**Comment by ghost** [comment]
Reopening now that the subway hall set exists, and will try to work on making at least the basic version of such an addon.
