### ISSUE TITLE
[SOLUTION IN COMMENTS] Script Error: attempt to concatenate a nil value (local 'text')

### ISSUE THREAD

**Issue by Ao1Pointblank** [obsidian-level-maker/Obsidian#435]
-- CONFIG FILE : OBSIDIAN V20"Unstable"
-- Build 2022.03.04
-- Based on OBLIGE Level Maker (C) 2006-2017 Andrew Apted
-- https://github.com/dashodanger/Obsidian/wiki

-- Obsidian (C) 2018-2022
-- MsrSgtShooterPerson
-- Armaetus
-- Garrett
-- Caligari87
-- Frozsoul
-- Simon-v
-- Beed28
-- Craneo
-- MogWaltz
-- EpicTyphlosion
-- Tapwave
-- Swedra
-- Demios
-- Scionox
-- josh771
-- dashodanger
-- Phytolizer
-- https://github.com/caligari87/ObAddon/

seed = 5117749799049339094                               

---- Game Settings ----

game = doom2
engine = zdoom
length = game
theme = bit_mixed

---- Architecture ----

float_size = Mix It Up
float_level_upper_bound = 75.0
float_level_lower_bound = 10.0
level_size_ramp_factor = 0.66
level_size_bias = default
mixin_type = normal
bool_prebuilt_levels = 1.0
outdoors = mixed
caves = mixed
liquids = mixed
hallways = mixed
teleporters = less
steepness = mixed
zdoom_vista = sky_gen_smart
zdoom_skybox = random

---- Map Build Options ----

bool_build_nodes_edge = 0.0

---- Combat ----

float_mons = Progressive
float_mix_it_up_upper_range = 2.0
float_mix_it_up_lower_range = 0.0
float_strength = 2.5
float_ramp_up = 1.0
bool_pistol_starts = 1.0
bool_quiet_start = 1.0
mon_variety = heaps
mon_variety_jumpstart = default
bosses = medium
bossesnormal = no
traps = mixed
trap_style = default
trap_qty = default
cages = rare
cage_qty = default
secret_monsters = no

---- Pickups ----

health = heaps
ammo = heaps
weapons = very_soon
items = more
secrets = less
secrets_bonus = heapsest

---- Map Build Options ----

bool_build_reject = 0.0

---- SLUMP Architecture ----

float_minrooms_slump = 15.0
float_bigify_slump = 50.0
float_forkiness_slump = 50.0
bool_dm_starts_slump = 0.0
bool_major_nukage_slump = 0.0
bool_immediate_monsters_slump = 1.0

---- SLUMP Monsters ----

slump_mons = normal

---- Map Build Options ----

bool_build_nodes_udmf = 1.0
map_format = udmf

---- Other Modules ----

@armaetus_epic_textures = 1
  bool_custom_liquids = 1.0
  custom_trees = zs
  environment_themes = random
  bool_include_package = 1.0
  bool_include_brightmaps = 1.0
  bool_no_env_theme_for_hell = 0.0

@debugger = 0

@doom_item_control = 0

@doom_mon_control = 0

@doom_weapon_control = 0

@export_map = 0

@fauna_module = 1
  bool_flies = 1.0
  bool_rats = 0.0

@gzdoom_marine_closets = 0

@iwad_mode = 0

@jokewad_module = 1
  bool_fireblu_mode = 0.0
  bool_pandemic_mode = 0.0

@misc = 1
  float_oblige5x_grammar = 0.0
  float_layout_absurdity = 10.0
  float_linear_mode = 0.0
  float_nature_mode = 15.0
  float_streets_mode = 15.0
  bool_urban_streets_mode = 1.0
  room_size_multiplier = 1.5
  room_area_multiplier = mixed
  room_size_consistency = mixed
  room_size_mix_type = normal
  room_area_mix_type = normal
  big_rooms = more
  big_outdoor_rooms = some
  room_heights = tall
  parks = more
  natural_parks = none
  park_detail = mixed
  windows = mixed
  passable_windows = not_on_vistas
  passable_railings = never
  symmetry = mixed
  beams = mixed
  fences = mixed
  porches = some
  scenics = mixed
  corner_style = themed
  liquid_sinks = yes
  darkness = mixed
  float_minimum_brightness = 0.0
  float_maximum_brightness = 256.0
  barrels = more
  doors = mixed
  keys = mixed
  trikeys = mixed
  switches = mixed
  local_switches = mixed
  bool_road_markings = 1.0
  street_traffic = mixed
  bool_exit_signs = 1.0
  linear_start = default
  dead_ends = some

@modded_game_extras = 1
  bool_hn_markers = 0.0
  bool_custom_actor_names = 0.0
  bool_qcde_lootboxes = 0.0
  bool_d4t_ents = 1.0
  bool_trailblazer = 0.0
  bool_complex_doom = 0.0

@prefab_control = 1
  bool_alt_starts = 0.0
  bool_foreshadowing_exit = 1.0
  bool_autodetail = 1.0
  point_prob = fab_default
  wall_prob = fab_default
  group_wall_prob = fab_default
  float_single_room_theme = 50.0
  float_limit_wall_groups = 50.0
  bool_peered_exits = 1.0
  steppy_caves = yes
  pf_crushers = 1
  pf_dexterity = 1
  pf_gamble = 1
  pf_sight_ambushes = 1
  pf_mirror_mazes = 1
  pf_dark_mazes = 1
  pf_stair_ladders = 1
  bool_jump_crouch = 1.0
  pf_damaging_halls = default
  bool_fab_match_theme = 1.0

@procedural_gotcha_zdoom = 0

@sky_generator = 1
  force_sky = 50
  force_hills = hs_random
  force_hill_params = hp_random
  cloud_color = default
  terrain_color = default
  nebula_color = default
  bool_influence_map_darkness = 0.0

@stealth_mon_control = 0

@stealth_mons = 0

@theme_ctl_doom2 = 0

@zdoom_ambient_sound = 1
  snd_start_id = 20000

@zdoom_marines = 0

@zdoom_specials = 1
  fog_generator = no
  fog_env = all
  fog_intensity = subtle
  bool_fog_affects_sky = 1.0
  bool_dynamic_lights = 1.0
  bool_glowing_flats = 1.0
  mapinfo_music_shuffler = yes
  story_generator = none
  bool_custom_quit_messages = 0.0
  generic_intermusic = $MUSIC_READ_M
  bool_episode_selection = 1.0
  bool_no_intermission = 0.0

-- END --

**Comment by Ao1Pointblank** [comment]
Above is the config i was using when i encountered the error,
Script Error: attempt to concatenate a nil value (local 'text')

From the log viewer:

****** ERROR OCCURRED ******
Stack Trace:  
1: ScriptMan_combine_script() @ script_manager.lua:39  
2: func() @ jokewad_module.lua:416  
3: ob_invoke_hook() @ oblige.lua:1604  
4: Level_make_all() @ level.lua:2962  
5: ob_build_cool_shit() @ oblige.lua:1776

Script Error: attempt to concatenate a nil value (local 'text')

**Comment by Ao1Pointblank** [comment]
*** Solution: ***
don't leave a submenu open / expanded if you have not clicked any of the checkboxes inside it! (leave it collapsed)

**Comment by ghost** [comment]
The version of Obsidian Unstable you are using is pretty out of date by this point, and line 416 in the current jokewad_module.lua doesn't even contain a function, so it's hard to tell what this might have been or if it's even still occurring. If you can replicate this with a current, fresh install (as in, do not unzip it over an existing directory), please open a new issue and attach that log.
