### ISSUE TITLE
[Request] mridlen's Oblige_Realm667 Addon for Obsidian

### ISSUE THREAD

**Issue by mattbratt11** [obsidian-level-maker/Obsidian#44]
I noticed a while ago when I tried to run the Realm667 Addon by mridlen for Obsidian, but for some reason, it had an unexpected error upon startup.
Is there any way that mridlen's Realm667 Addon can be added to Obsidian in the next build?
I would gladly appreciate it.
Keep it up.

**Comment by ghost** [comment]
It's likely the change from Lua 5.1->5.4, which will render older scripts unable to load.
About distributing it WITH Obsidian, I'm not sure, but I'm willing to work on providing the creator with converted Lua files.

Not sure on the exact timeframe though; I can't promise that releases won't happen before that's done.

**Comment by ghost** [comment]
Rename the following file to realm_667.pk3 and place it in the addons folder for Obsidian
After creating a WAD, follow the usual instructions for the Realm 667 mod. 
Tested with Beta 15.
(Attachment removed to be placed in separate personal addon repo)

If this works for you, let me know and I'll close the Issue.

**Comment by mattbratt11** [comment]
[Obsidian_Realm667_Report.zip](https://github.com/dashodanger/Oblige/files/6255656/Obsidian_Realm667_Report.zip)
I have a script error reported in this attachment. Is there any way for you to fix it?

**Comment by ghost** [comment]
(Attachment removed - changes now in mainline Obsidian)

I believe it was an issue with the export_map.lua file. I've provided a replacement that should go in the /modules directory.
Does the Realm 667 addon work if you disable exporting to MAP format? I'd like to work these as separate issues if possible.

**Comment by mattbratt11** [comment]
[Obsidian_Realm667_Report.zip](https://github.com/dashodanger/Oblige/files/6256134/Obsidian_Realm667_Report.zip)
Report Updated: New Error.

**Comment by ghost** [comment]
Please disable the Export MAP module and test the Realm 667 addon without it. If that works, then I will close this issue and start a new one with your other errors.

**Comment by mattbratt11** [comment]
I turned off the export maps feature, and it works like a charm. I used Obsidian Beta 15.
Thanks.

**Comment by ghost** [comment]
Sounds good, I'll open a new issue with your existing logs. Thanks.
