### ISSUE TITLE
Feature Requst: The ability to automatically append the compatibility level to the end of the WAD name.

### ISSUE THREAD

**Issue by yum13241** [obsidian-level-maker/Obsidian#445]
Eg. If I generated a megawad for PRBOOM say, let's call it Deathly Shadows.

normally OBSIDIAN would do something like this:

doom2_deathly_shadows.wad

I would have to add -PRBOOM- to the end for me to tell what it was generated for.
eg. doom2_deathly_shadows-PRBOOM-.wad

The problem is that doing that manually is a pain.

I would like OBSIDIAN to have an option to do that automatically. It would save a LOT of time.

**Comment by ghost** [comment]
I don't think we'll be offering suffixes, but making the engine available as a part of the prefix format is a reasonable ask. I'll post updates as this is added.

**Comment by ghost** [comment]
Builds after https://github.com/dashodanger/Obsidian/commit/4cb1fa6c0ecb892801e01b8b4d3e91253884040a should now have the "Engine" option exposed for use in the filename formatter. For your particular use case, I would recommend selecting "Custom" from the File->Options->Filename Prefix, and then use %g_%e_ with the "Set Custom Prefix..." dialog. This should give you filenames like:
doom2_prboom_deathly_shadows.wad

**Comment by yum13241** [comment]
Thanks!
