### ISSUE TITLE
Error on Build "attempt to index field 'wide halls' (a nil value)"

### ISSUE THREAD

**Issue by Wackhairdoo** [obsidian-level-maker/Obsidian#454]
Initial episode list = 
{
  1 = deimos
  2 = hell
  3 = tech
  4 = flesh
}
Grown episode list = 
{
  1 = deimos
  2 = hell
  3 = tech
  4 = flesh
}
Theme for level E1M1 = tech
Sky generator:
Forced sky: sky_default
Sky theme: urban
  1 = BROWN_CLOUDS
    + TAN_HILLS
Special levels:
  none
Initial size for E1M1: 27
size_multiplier: 0.5
area_multiplier: 1
size_consistency: normal
Game title: Hexa Doken's Doom
Game sub-title: Billions of Potential Levels!
Episode 1 title: Fire With Fire
Planned weapons:
E1M1
  new    = { plasma, bfg, launch, shotty, chain }
  start  = { shotty }
  other  = { plasma, bfg, launch, shotty, chain }
  secret = NONE
  quota  = 3
Planned monsters:
E1M1
  level = 4.89
  new  = { shooter, zombie, imp }
  pal  = { imp, shooter, zombie }
  skip = {}
  b_quotas = { 0, 0, 0 }
  bosses = {}
Level 1 title: Mexbruniko Research Compound
~~~~~~| E1M1 |~~~~~~
****** ERROR OCCURRED ******
Stack Trace:
  1: func() @ zdoom_armaetus_epic_textures.lua:825
  2: ob_invoke_hook() @ oblige.lua:1610
  3: Level_make_level() @ level.lua:2695
  4: Level_make_all() @ level.lua:2767
  5: ob_build_cool_shit() @ oblige.lua:1778
Script Error: attempt to index field 'wide_halls' (a nil value)
Writing WAD directory
Closed WAD file

**Comment by Wackhairdoo** [comment]
The rest consists of loading a few hundred prefab files before getting to another portion of settings then more prefabs before the rest

**Comment by ghost** [comment]
A few quick questions to help troubleshoot:
1. Can you post the actual complete LOGS.txt file?
2. Which version are you using?
3. When you update the program, are you unzipping new releases over the same directory?

**Comment by Wackhairdoo** [comment]
I have yet to need an update as I just installed today V20 unstable

**Comment by Wackhairdoo** [comment]
[LOGS - Copy.txt](https://github.com/dashodanger/Obsidian/files/8963482/LOGS.-.Copy.txt)

**Comment by Wackhairdoo** [comment]
sorry for the late response

**Comment by ghost** [comment]
https://github.com/dashodanger/Obsidian/commit/647992ae0653b0504c3c5ab4de46a678a529fa42 should fix this. If you don't want to wait until a new release, you can grab /modules/zdoom_armaetus_epic_textures.lua from the repo and overwrite your local copy. Alternatively, you could use Doom II instead of Ultimate Doom until the next release.

**Comment by Wackhairdoo** [comment]
Huge thanks for the fast responses!
