### ISSUE TITLE
Nil value error

### ISSUE THREAD

**Issue by FistsAkimbo** [obsidian-level-maker/Obsidian#508]
Getting a consistent WAD generation failure at Map 30 consistently, with the current unstable build (from 16 hours ago,) along with the version just prior. Happens with the default config or my usual tweaks.

Log is attached.
[Unstable Build Crash.txt](https://github.com/dashodanger/Obsidian/files/9737722/Unstable.Build.Crash.txt)

**Comment by ghost** [comment]
I'm guessing it's probably been resolved by https://github.com/dashodanger/Obsidian/commit/dce0cc0730d9a8d03fd5e62fd4f4fc3b81247fea, as I encountered a similar issue when leaving Prebuilt Levels on. It should be good in the next release, or if you want to grab the files from the current repo I imagine that would do the trick as well.

**Comment by FistsAkimbo** [comment]
Genuinely appreciate your super fast, helpful responses. Out of curiosity, other than the Icon of Sin, what other instances occur in any of the supported games where a pre-built map is used?

I'll also see about providing an example in that other bug thread of mine and get that progressed, appreciate your help.

**Comment by FistsAkimbo** [comment]
Just a heads up, that commit seems to break Obsidian even more, as with all five files patched over (though level.lua seems to be the only offender,) it just has an error on program start. It's as follows:

Unable to load script '"scripts\\level.lua"'
scripts/level.lua:8: unexpected symbol near '<' 

Assuming though, that the commit was the only files needed for this change.

EDIT: just noticed the level.lua fix commit after the one you linked, used that, and it solved the issue, thanks!

**Comment by ghost** [comment]
Ahhh, gotcha. Sorry, these bugs are going to sneak in for a little bit. Without boring you, we had to change a ton of functions involving a table called LEVEL which has caused a lot of this sort of thing lately. We tried to catch most of them ahead of time, but the nature of our RNG makes it that so certain functions aren't necessarily called during a run and thus might go unnoticed, or in this case if a certain module/option isn't enabled.

**Comment by ghost** [comment]
I'm gonna close this one as I believe the release I posted this morning has all of these fixes rolled into it. If not, I can reopen it.
