### ISSUE TITLE
Map gen fails when "Export MAP File" option is selected

### ISSUE THREAD

**Issue by ghost** [obsidian-level-maker/Obsidian#53]
From existing logs:
-snip-
****** ERROR OCCURRED ******

Stack Trace:
  1: c-function format()
  2: export_printf() @ export_map.lua:23
  3: add_entity_func() @ export_map.lua:139
  4: raw_add_entity() @ brush.lua:68
  5: Fab_render() @ prefab.lua:789
  6: Fabricate() @ prefab.lua:2316
  7: Render_chunk() @ render.lua:2735
  8: visit_chunk() @ render.lua:2834
  9: Render_all_chunks() @ render.lua:2849
  10: Room_build_all() @ room.lua:4197
  11: Level_build_it() @ level.lua:2762
  12: Level_make_level() @ level.lua:2901
  13: Level_make_all() @ level.lua:2975
  14: ob_build_cool_shit() @ oblige.lua:1429

Script Error: bad argument #3 to 'format' (number has no integer representation)

**Comment by ghost** [comment]
(Attached file removed - changes now in mainline Obsidian)

I was able to export a .map file successfully with this version of export_map.lua. Let me know how it goes.

**Comment by mattbratt11** [comment]
It works now. Thanks for the fix.
