### ISSUE TITLE
symbol not found in flat namespace '_CGBitmapContextCreate'

### ISSUE THREAD

**Issue by Kishinskiy** [obsidian-level-maker/Obsidian#584]
I have Error after build.

Build  Successful but wen i try start application, i get error message

❯ ./obsidian
dyld[7325]: symbol not found in flat namespace '_CGBitmapContextCreate'
[1]    7325 abort      ./obsidian

MacOS 13.2.1

**Comment by ghost** [comment]
None of us have a Mac to test on, but I think it's an issue with the CMake file at the moment. I'll try a few tests using the CI builds.

**Comment by ghost** [comment]
https://github.com/obsidian-level-maker/Obsidian/commit/b110e992d66f5b1380397a83de7a9b91c1526ff8 seems to compile and link properly via the MacOS CI. I would try to update to this commit and re-compile (probably with a fresh build folder). If that works, I'll close this.

**Comment by ghost** [comment]
As far as I can tell from our CI builds, the proper linking is in place, so I'll close this for now. It can be reopened if you discover that library links are still missing.
