### ISSUE TITLE
Blocked Hallway Exit Due To Decoration Prefab

### ISSUE THREAD

**Issue by SpencerBelleau** [obsidian-level-maker/Obsidian#603]
[LOGS.txt](https://github.com/obsidian-level-maker/Obsidian/files/11727749/LOGS.txt)
![Screenshot_Doom_20230612_155131](https://github.com/obsidian-level-maker/Obsidian/assets/9222639/89543a63-4688-4456-878a-ea544293001d)
Logs attached, changed my username but turns out it was pointless because my GH username is the same as my PC one :^)
Basically, on MAP27 you can't get out of the start area because the exit to the sky hallway that leads out is blocked by a torch that was placed by a decoration prefab. Never had this happen before so it must be super rare. Not a big deal IMO but maybe something to patch in next release.
Sorry if this is the wrong place to report, hopefully it gets to the right people.

**Comment by SpencerBelleau** [comment]
Actually, upon further inspection, this is a switch, not a decoration.

**Comment by ghost** [comment]
Shooter addressed this in Unstable and the fix has been backported to Stable as of https://github.com/obsidian-level-maker/Obsidian/commit/bba69a31091b24fbdf96f091dd9d445d1737b7f7
