### ISSUE TITLE
Generated Zdoom maps contain GZdoom-specific stuff

### ISSUE THREAD

**Issue by Alexander230** [obsidian-level-maker/Obsidian#604]
Please make a separate option for Zandronum or vanilla Zdoom compatibility; now maps generated for Zdoom can be loaded only in GZdoom.

**Comment by ghost** [comment]
I have addressed this in Unstable with https://github.com/obsidian-level-maker/Obsidian/commit/80f177153036198e7b6da3a362eecfaaa77863a9 and changed the name of the 'ZDoom Family' to 'GZDoom' again to prevent confusion. We do not specifically target Zandronum or Legacy ZDoom; the original intent of calling it 'ZDoom Family' was to account for variants such as LZDoom and QZDoom.

Maps generated for the other options (Boom-compatible, etc) should work fine with either of the ports you mention.
