### ISSUE TITLE
Compile error: error: 'Window' does not name a type; did you mean 'Fl_Window'?

### ISSUE THREAD

**Issue by weberam2** [obsidian-level-maker/Obsidian#607]
I am a linux user, running Ubuntu 22.04.2 LTS

These are the steps I was performing:
```
gh repo clone obsidian-level-maker/Obsidian
```

```
cmake --version
```
gave me: cmake version 3.22.1

then I tried running:
```
cmake --build --preset dist
```

But got the following error:

> Consolidate compiler generated dependencies of target miniz
[  0%] Built target miniz
Consolidate compiler generated dependencies of target obsidian_zdbsp
[  2%] Built target obsidian_zdbsp
Consolidate compiler generated dependencies of target filename_formatter
[  3%] Built target filename_formatter
Consolidate compiler generated dependencies of target fltk_z
[  6%] Built target fltk_z
Consolidate compiler generated dependencies of target fltk_jpeg
[ 15%] Built target fltk_jpeg
Consolidate compiler generated dependencies of target fltk_png
[ 21%] Built target fltk_png
Consolidate compiler generated dependencies of target fltk
[ 21%] Building CXX object source_files/fltk/src/CMakeFiles/fltk.dir/Fl.cxx.o
In file included from /home/weberam2/Games/Obsidian/source_files/fltk/src/Fl.cxx:22:
/home/weberam2/Games/Obsidian/source_files/fltk/FL/platform.H:68:8: error: 'Window' does not name a type; did you mean 'Fl_Window'?
   68 | inline Window fl_xid(const Fl_Window* w) { Fl_X *xTemp = Fl_X::flx(w); return xTemp ? (Window)xTemp->xid : 0; }
      |        ^~~~~~
      |        Fl_Window
/home/weberam2/Games/Obsidian/source_files/fltk/FL/platform.H:74:29: warning: 'fl_find' initialized and declared 'extern'
   74 | extern FL_EXPORT Fl_Window* fl_find(Window xid);
      |                             ^~~~~~~
/home/weberam2/Games/Obsidian/source_files/fltk/FL/platform.H:74:37: error: 'Window' was not declared in this scope
   74 | extern FL_EXPORT Fl_Window* fl_find(Window xid);
      |                                     ^~~~~~
/home/weberam2/Games/Obsidian/source_files/fltk/FL/platform.H:77:18: error: 'Window' does not name a type; did you mean 'Fl_Window'?
   77 | extern FL_EXPORT Window fl_window;
      |                  ^~~~~~
      |                  Fl_Window
/home/weberam2/Games/Obsidian/source_files/fltk/src/Fl.cxx:702:12: error: redefinition of 'Fl_Window* fl_find'
  702 | Fl_Window* fl_find(Window xid) {
      |            ^~~~~~~
In file included from /home/weberam2/Games/Obsidian/source_files/fltk/src/Fl.cxx:22:
/home/weberam2/Games/Obsidian/source_files/fltk/FL/platform.H:74:29: note: 'Fl_Window* fl_find' previously defined here
   74 | extern FL_EXPORT Fl_Window* fl_find(Window xid);
      |                             ^~~~~~~
/home/weberam2/Games/Obsidian/source_files/fltk/src/Fl.cxx:702:20: error: 'Window' was not declared in this scope
  702 | Fl_Window* fl_find(Window xid) {
      |                    ^~~~~~
/home/weberam2/Games/Obsidian/source_files/fltk/src/Fl.cxx:2162:11: error: 'Window' does not name a type; did you mean 'Fl_Window'?
 2162 | FL_EXPORT Window fl_xid_(const Fl_Window *w) {
      |           ^~~~~~
      |           Fl_Window
gmake[2]: *** [source_files/fltk/src/CMakeFiles/fltk.dir/build.make:76: source_files/fltk/src/CMakeFiles/fltk.dir/Fl.cxx.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:560: source_files/fltk/src/CMakeFiles/fltk.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2

Any ideas?

**Comment by ghost** [comment]
Our Linux CI builds are run against 22.04, so that's a bit puzzling. 
- Are you on an unusual architecture?
- Are you running Wayland or X11, or a hybrid of the two?
- Did you ensure that you have the dependencies in COMPILING.md installed?

**Comment by ghost** [comment]
If you're willing to try compiling the unstable branch, I've synced the included FLTK with upstream as of this morning. That might also help your issue.

**Comment by weberam2** [comment]
Hi Sorry! I've been meaning to get to this but have just been busy. Thank you for being so quick to respond!
Let me get back to you sometime this week

**Comment by ghost** [comment]
I was able to recreate this on Debian 12, and it looks like the installation of libx11-dev in addition to the other libraries listed in COMPILING.md solved the issue. If you're on Wayland, you'll have to ensure that the necessary packages are installed, as outlined in source_files/fltk/README.Wayland.txt.
