### ISSUE TITLE
Not Work Addons For Obsidian Level Maker 21 30.07.2023

### ISSUE THREAD

**Issue by mihail2245** [obsidian-level-maker/Obsidian#620]
Hello. There was a problem in the latest version of the obsidian 21 level generator from 07/30/2023. When I try to activate them, I get the error No folders or *oaf files found in the /addons directory. How can I fix this problem?

**Comment by ghost** [comment]
You will need to rename the extension to .oaf, or alternately extract the contents into a folder and place that folder under /addons. Once v21 becomes the stable release, the downloads from the Addons page will have their extensions updated accordingly.
