### ISSUE TITLE
Levels are not generated for Doom 1

### ISSUE THREAD

**Issue by mihail2245** [obsidian-level-maker/Obsidian#637]
When creating levels to When creating levels for the first part of the game, the following error occurs. Is it possible to fix this? When creating levels for the first part of the game, the following error occurs. Is it possible to fix this? ![IMG_20231124_151142](https://github.com/obsidian-level-maker/Obsidian/assets/113275019/15557d2b-773f-448b-944f-242ef28d9946)

**Comment by ghost** [comment]
If you don't want to wait for the next release to have this fixed, you can change line #10625 of games/doom/x_doom1.lua to read
`gui.debugf("Monster %s : power %f\n", name, info.pow)`

Instead of 
`gui.debugf("Monster %s : power %d\n", name, info.pow)`

**Comment by ghost** [comment]
Fixed in Unstable with https://github.com/obsidian-level-maker/Obsidian/commit/cf4fb2aea815066211cf5f90410440f6514739fd; this should not affect v20 as it is still using LuaJIT
