### ISSUE TITLE
[Feature] Level extension

### ISSUE THREAD

**Issue by Jenoclip** [obsidian-level-maker/Obsidian#639]
I've been thinking with my comrades for a while and we realized that obsidian needs such a thing as a

# An addition to the existing levels
Instead of a completely new level, you can take existing levels (several from the .wad or .pk3 package) and Obsidian will generate details on top of the level (i.e. extend level along edges of geometry and add some details to the level itself), I would like to see such a thing with a dialog box for selecting specific levels (and preferably that you could select several at once).

_Is it a good idea or a bad one?_

**Comment by ghost** [comment]
Modifying existing mapsets is not a goal of Obsidian; we have plenty of work to do regarding the quality of our own generation before trying to arbitrarily modify other peoples' work.
