### ISSUE TITLE
Unable to load script '"scripts\\defs.lua"'

### ISSUE THREAD

**Issue by jadenquinn** [obsidian-level-maker/Obsidian#641]
I can't actually copy and paste the text, so I'll just provide a screenshot. I have literally no other info to add to this, other than that this is the error I get when trying to open Obsidian for the 2nd time. It opened the first time, and it was a lil buggy but eventually I generated a level, and closed it. Now it won't open again.
![image](https://github.com/obsidian-level-maker/Obsidian/assets/13245331/93184610-ee03-4c73-b2f8-365061798b2b)

**Comment by ghost** [comment]
Closing this because I believe it is the unintentional use of ObAddon that you mentioned in the Discord server. I can re-open if I'm mistaken.
