### ISSUE TITLE
Feature request: Only show "rollback" icon when a setting's value is non-default

### ISSUE THREAD

**Issue by thecnoNSMB** [obsidian-level-maker/Obsidian#649]
As in title; I don't know what the default values are so I don't know what values (if any) I may have accidentally changed. I believe hiding the "reset to default" button when the value is already default is the usual way of indicating this.

**Comment by ghost** [comment]
The GUI currently in use is deprecated and will no longer be developed; in the unstable branch I have removed these windows/widgets and the FLTK dependency altogether in favor of a ground-up rework using ImGUI.
