### ISSUE TITLE
Build error: "implicit declaration of function ‘isatty’ [-Wimplicit-function-declaration]"

### ISSUE THREAD

**Issue by Slider-Whistle** [obsidian-level-maker/Obsidian#662]
```
[  4%] Building C object source_files/filename_formatter/CMakeFiles/filename_formatter.dir/lex.yy.c.o
lex.yy.c: In function ‘yy_init_buffer’:
lex.yy.c:1407:36: error: implicit declaration of function ‘isatty’ [-Wimplicit-function-declaration]
make[2]: *** [source_files/filename_formatter/CMakeFiles/filename_formatter.dir/build.make:90: source_files/filename_formatter/CMakeFiles/filename_formatter.dir/lex.yy.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:394: source_files/filename_formatter/CMakeFiles/filename_formatter.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```
I'm not a programmer, but I found on a random mailing list that it has something to do with including unistd: https://opensips.org/pipermail/devel/2015-March/016738.html
Just as a haphazard test to check whether it would make the program build, I copied lex.yy.c:443's `#include <unistd.h>` to the top of the file instead. I have no idea what consequences this might have on the program during runtime, but it successfully built.

**Comment by ghost** [comment]
In the v21 branch I just did away with the isatty check altogether since it covers a situation that filename_formatter shouldn't encounter. I'll go ahead and backport the same tweak to this branch and let you know when it's ready for testing.

**Comment by ghost** [comment]
https://github.com/obsidian-level-maker/Obsidian/commit/12df6793145a8d3287be10631b87567bac25a49e is ready to test

**Comment by ghost** [comment]
As far as I can tell, this is good; going to go ahead and close it but feel free to reopen if needed.

**Comment by Slider-Whistle** [comment]
Oh, pardon. Yeah, no build issues on my end once I apply that patch.
