### ISSUE TITLE
Can't generate wad in current unstable release (2024.07.26)

### ISSUE THREAD

**Issue by 4-and-a-half-star-games** [obsidian-level-maker/Obsidian#666]
Every time I try to generate a wad I get the error "Script Error: : attempt to call a nil value (field 'check_simple_mode')"

**Comment by ghost** [comment]
Fixed with https://github.com/obsidian-level-maker/Obsidian/commit/17f3359ad3309e41a8636674a083a3d126448556; you will want to grab the "/modules/miscellaneous.lua" file from the repo or wait until I can get the release packages updated.
