### ISSUE TITLE
Latest unstable build marked as Trojan by Windows Defender.

### ISSUE THREAD

**Issue by 4-and-a-half-star-games** [obsidian-level-maker/Obsidian#675]
Never had this issue before, Chrome won't even download it, I'm assuming it's a false positive, but idk.

**Comment by ghost** [comment]
This happens on and off with various builds; the only steps I can suggest are to ensure that the SHA-256 hash for the download matches what is posted on the Release page (these should also match the hash in the artifact upload step with the CI workflows that produce the release builds, such as https://github.com/obsidian-level-maker/Obsidian/actions/runs/11526651539). These hashes, or the files themselves, can be submitted to things like VirusTotal to see if it matches any of the detections you are seeing.

As far as it being a false positive, I would be a pretty biased source to tell you that it is; those kind of trust decisions are for the end-user to make.
