### ISSUE TITLE
Generation of a subway based on the generation of a city with roads

### ISSUE THREAD

**Issue by HytaleAdrRus** [obsidian-level-maker/Obsidian#71]
I wanted to have the same metro generation as the generation of a city with streets and roads but a separate function and underground with elevators with technical exits with metro stations with turnstiles and tunnels themselves with reals and transfer hubs

**Comment by Armaetus** [comment]
There are higher priorities right now, but it _might_ be considered later on.

**Comment by ghost** [comment]
I'm going to close this as we have since introduced the gtd_subway and metro hallway sets. These themes and prefabs will continue to evolve, but I think this is the sort of thing that could be open-ended forever and thus not necessary to keep active in the issue tracker.
