### ISSUE TITLE
Feature Request: Add Mapset Name/Subtitle to LANGUAGE lump

### ISSUE THREAD

**Issue by TheKins** [obsidian-level-maker/Obsidian#87]
Hey there,

Is there any chance of the randomly-generated name (and possibly subtitle) for the mapset to be added to LANGUAGE for mods to peer at? I messed around with an OBLIGE-centric titlemap for DRLA that displays the titlepic graphic quite a while back, it might be fun to instead display the text using fancy custom fonts and tricks in a project I've been pondering...

**Comment by GTD-Carthage** [comment]
Definitely doable!
